services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: lokascore
      POSTGRES_PASSWORD: lokascore
      POSTGRES_DB: lokascore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ../../apps/api
    env_file:
      - ../../apps/api/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
  web:
    build: ../../apps/web
    env_file:
      - ../../apps/web/.env
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  db_data:
